### ISSUE TITLE
Error when loading split released models for inference on custom data

### ISSUE THREAD

**Issue by ysig** [pedropro/TACO#20] opened 2020-06-26 16:21 UTC
I get the following error wen I try to use the pretrained detectors found in releases (https://github.com/pedropro/TACO/releases/tag/1.0).

```
  File /TACO/detector/model.py", line 2235, in load_weights
     topology.load_weights_from_hdf5_group_by_name(f, layers)
   File "/miniconda3/envs/taco/lib/python3.6/site-packages/keras/engine/topology.py", line 3479, in load_weights_from_hdf5_group_by_name
     K.batch_set_value(weight_value_tuples)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2372, in batch_set_value
     assign_op = x.assign(assign_placeholder)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign
     name=name)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
     validate_shape=validate_shape)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
     use_locking=use_locking, name=name)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
     op_def=op_def)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
     return func(*args, **kwargs)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
     op_def=op_def)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
     control_input_ops)
   File "miniconda3/envs/taco/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
     raise ValueError(str(e))
 ValueError: Dimension 1 in both shapes must be equal, but are 256 and 44. Shapes are [1024,256] and [1024,44]. for 'Assign_376' (op: 'Assign') with input shapes: [1024,256], [1024,44].
```
I use keras 2.1.6 and tensorflow 1.13.1 
My Config look like this:

```
Configurations:
BACKBONE                       resnet50
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
DETECTION_CLASSLESS_NMS_THRESHOLD 0.9
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0
DETECTION_NMS_THRESHOLD        0.3
DETECTION_SCORE_RATIO          True
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                76
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MASK_SHARE                     False
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (512, 512)
NAME                           taco
NUM_CLASSES                    64
OPTIMIZER                      SGD
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  False
USE_OBJECT_ZOOM                False
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001
ZOOM_IN_FREQ                   0.5
```

and I used `--class_map=taco_config/map_10.csv` for inference.

**Comment by alexweininger** [comment] 2020-10-26 16:21
Same for me :(

**Comment by pedropro** [comment] 2020-11-15 20:43
Duplicate of #17

**Closed by pedropro** 2020-11-15 20:43 UTC

**Comment by Michsh** [comment] 2021-06-17 13:23
Error on testing after training.

`python3 detector.py test --dataset=../data --model=models/logs/taco20210617T0019/mask_rcnn_taco_0100.h5 --round 0 --class_map=./taco_config/my_map.csv 

WARNING:tensorflow:From /home/TACO-master/detector/model.py:816: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Traceback (most recent call last):
  File "detector.py", line 289, in <module>
    _, model_path = model.get_last_checkpoint(args.model)
  **File "/home/TACO-master/detector/model.py", line 2167, in get_last_checkpoint
    assert model_name in dir_names
AssertionError**`

I have :
Python 3.6.9
Tensorflow 1.14.0
 Keras  2.1.6
